import { StyleSheet } from "react-native";

const NAVY = "#182C4D";
const BLUE = "#4775E7";

export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#F4F7FC" },

  header: {
    backgroundColor: NAVY,
    paddingHorizontal: 22,
    paddingTop: 16,
    paddingBottom: 20,
  },
  headerTitle: { color: "#c4d7f5", fontSize: 24, fontWeight: "800" },
  back: { color: "#C7D9FF", fontSize: 15, marginBottom: 8 },
  content: { padding: 20, flexGrow: 1 },
  hero: { fontSize: 24, fontWeight: "800", color: NAVY, marginBottom: 8 },
  subtitle: { color: "#697B93", marginBottom: 20 },
  stats: { flexDirection: "row", gap: 10, marginBottom: 20 },
  stat: {
    flex: 1,
    padding: 15,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#c4d7f5",
    backgroundColor: "white",
    alignItems: "center",
  },
  statNumber: { fontSize: 26, fontWeight: "800", color: NAVY },
  muted: { color: "#697B93", fontSize: 12, marginTop: 4 },
  sectionTitle: {
    color: NAVY,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 22,
    marginBottom: 12,
  },
  primaryButton: {
    padding: 15,
    backgroundColor: BLUE,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 10,
  },
  primaryText: { color: "white", fontWeight: "700", fontSize: 15 },
  taskRow: {
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderRadius: 14,
    marginBottom: 10,
    gap: 12,
    borderWidth: 1,
    borderColor: "#E8EDF5",
  },
  circle: {
    borderWidth: 2,
    borderColor: BLUE,
    width: 26,
    height: 26,
    borderRadius: 13,
    justifyContent: "center",
    alignItems: "center",
  },
  checked: { backgroundColor: "#279772", borderColor: "#279772" },
  checkText: { color: "white", fontWeight: "800" },
  taskTitle: { color: NAVY, fontWeight: "700", fontSize: 15 },
  crossed: { textDecorationLine: "line-through", color: "#8B98AC" },
  arrow: { fontSize: 26, color: "#9AA7BB" },
  filters: { gap: 8, paddingBottom: 14 },
  chip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#DFE7F3",
  },
  activeChip: { backgroundColor: NAVY, borderColor: NAVY },
  chipText: { color: NAVY, fontSize: 13, fontWeight: "600" },
  activeChipText: { color: "white" },
  sortButton: { alignSelf: "flex-end", marginBottom: 16 },
  sortText: { color: BLUE, fontWeight: "700" },
  fieldLabel: {
    color: "#63748E",
    fontWeight: "800",
    fontSize: 12,
    marginTop: 15,
    marginBottom: 9,
  },
  fieldValue: { color: NAVY, fontSize: 16, marginBottom: 6 },
  detailCard: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 15,
    marginVertical: 18,
  },
  input: {
    backgroundColor: "white",
    padding: 15,
    borderRadius: 12,
    fontSize: 15,
    borderColor: "#DCE5F2",
    borderWidth: 1,
  },
  subjectGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
});
